name: Fork Sync V2

on:
  schedule:
    - cron: '* * * * *' # This runs the job every minute

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2     
        
      - name: Set User Name
        run: git config --global user.name "Arun R Variyath"
        
      - name: Set Mail Id
        run: git config --global user.email "32630496+arunvariyath@users.noreply.github.com"
        
      - name: Set upstream remote
        run: git remote add upstream https://github.com/Hamza417/Inure.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/master --no-edit --allow-unrelated-histories

      - name: Push changes to fork
        run: git push origin master
